version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      ES_JASVA_OPTS: "-Xms 2g -Xmx 2g"
    networks:
      - ELK
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /data/elasticsearch:/usr/share/elasticseasrch/data
      - /data/elasticsearch/plugin:/usr/share/elasticsearch/plugins
  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    ports:
      - "5000:5000"
      - "9600:9600"
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    networks:
      - ELK
    depends_on:
      - elasticsearch

  apm:
    image: docker.elastic.co/apm/apm-server:7.2.0
    ports:
      - 8200:8200
    volumes:
      - ./apm-server/config/apm-server.yml:/usr/share/apm-server/apm-server.yml
    networks:
      - ELK
    depends_on:
      - elasticsearch
      - kibana

networks:
  ELK:
    driver: bridge