# Use root/example as user/password credentials
version: '3.1'

services:
    gitlab:
      image: 'gitlab/gitlab-ce:latest'
      container_name: gitlab-server
      restart: always
      hostname: 'gitlab.local.com'
      environment:
        GITLAB_OMNIBUS_CONFIG: |
          external_url 'http://gitlab.local.com:8929'
          gitlab_rails['gitlab_shell_ssh_port'] = 2224
      ports:
        - '8929:8929'
        - '2224:22'
      volumes:
        - '/opt/docker/volumes/gitlab/config:/etc/gitlab'
        - '/opt/docker/volumes/gitlab/logs:/var/log/gitlab'
        - '/opt/docker/volumes/gitlab/data:/var/opt/gitlab'
